CREATE TABLE deadline (
deadline_id INTEGER PRIMARY KEY AUTOINCREMENT,
subject VARCHAR(255) NOT NULL, 
task VARCHAR(255) NOT NULL, 
deadline_date DATE NOT NULL,
priority INTEGER, 
state VARCHAR(255) NOT NULL, 
note TEXT NOT NULL,
is_deleted BOOLEAN NOT NULL DEFAULT FALSE);
